all:
	@echo "\nDec 1st"
	runghc dec1.hs

	@echo "\nDec 2nd"
	runghc dec2.hs

	@echo "\nDec 3rd"
	runghc dec3.hs

	@echo "\nDec 4th"
	runghc dec4.hs

	@echo "\nDec 5th"
	runghc dec5.hs

	@echo "\nDec 7th"
	runghc dec7.hs

	@echo "\nDec 8th"
	runghc dec8.hs
