
.PHONY: all clean

all:
	gcc -Wall longestCommonPrefix.c -o longestCommonPrefixC && ./longestCommonPrefixC
	g++ -Wall longestCommonPrefix.cpp -o longestCommonPrefixCPP && ./longestCommonPrefixCPP

clean:
	rm -f *.o *~ longestCommonPrefixC longestCommonPrefixCPP
